mode: development # Use "hyde publish -c prod.yaml to have this automatically switch to production
media_root: media # Relative path from content folder.
media_url: /media # URL where the media files are served from.
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.sorter.SorterPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
context:
    data:
        site_title: GregHaynes.net
        author:
            name: Gregory Haynes
            url: "http://greghaynes.net"
        google_analytics_id: UA-XXXXX-YY
        home_url: /index.html
        menu:
            - title: Projects
              url: /projects.html
            - title: Blog
              url: /blog/index.html
              type: node
meta:
    nodemeta: meta.yaml
    created: !!timestamp 2013-01-01 00:00:00
    author: Gregory Haynes
sorter:
    time:
        attr:
            - meta.created
        reverse: true
        filters:
            source.kind: html
            meta.listable: true
